import QuotationWire

/-!
A restricted, executable Enderton proof checker for the local equality
certificates generated by the quotation compiler. Its only axiom cases are
the universal generalization of x=x and its closed-term instantiation axiom;
modus ponens uses actual earlier line indices. These are Enderton-valid cases.

It is deliberately not called a complete PA-bin checker. In particular it
does not implement propositional tautology recognition, arithmetic induction,
the proof-code predicate Bew, or arithmetic proofs of checker correctness.
-/

set_option autoImplicit false
set_option warningAsError true

namespace MAISO11.Quotation

/-- Ordinary expanded, closed PA terms, with efficient numeral constructors. -/
inductive ClosedTerm where
  | zero : ClosedTerm
  | bit0 : ClosedTerm → ClosedTerm
  | bit1 : ClosedTerm → ClosedTerm
  | add : ClosedTerm → ClosedTerm → ClosedTerm
  | mul : ClosedTerm → ClosedTerm → ClosedTerm
  deriving DecidableEq, Repr

def ClosedTerm.eval : ClosedTerm → Nat
  | .zero => 0
  | .bit0 x => 2 * x.eval
  | .bit1 x => 2 * x.eval + 1
  | .add x y => x.eval + y.eval
  | .mul x y => x.eval * y.eval

def numeralTermBits : List Bool → ClosedTerm
  | [] => .zero
  | false :: bs => .bit0 (numeralTermBits bs)
  | true :: bs => .bit1 (numeralTermBits bs)

theorem numeralTermBits_eval (bs : List Bool) :
    (numeralTermBits bs).eval = bitValue bs := by
  induction bs with
  | nil => rfl
  | cons b bs ih => cases b <;> simp [numeralTermBits, ClosedTerm.eval, bitValue, ih]

def numeralTerm (n : Nat) : ClosedTerm := numeralTermBits (bits n)

theorem numeralTerm_eval (n : Nat) : (numeralTerm n).eval = n := by
  simp [numeralTerm, numeralTermBits_eval, bits_value]

structure TermTriple where
  len : ClosedTerm
  scale : ClosedTerm
  payload : ClosedTerm
  deriving DecidableEq, Repr

def TermTriple.get (t : TermTriple) : Slot → ClosedTerm
  | .len => t.len
  | .scale => t.scale
  | .payload => t.payload

def TermTriple.eval (t : TermTriple) : Value := ⟨t.len.eval, t.scale.eval, t.payload.eval⟩

theorem TermTriple.get_eval (t : TermTriple) (s : Slot) :
    (t.get s).eval = t.eval.get s := by cases s <;> rfl

def Expr.expand {n : Nat} (ρ : Fin n → TermTriple) : Expr n → ClosedTerm
  | .num k => numeralTerm k
  | .ref i s => (ρ i).get s
  | .add x y => .add (x.expand ρ) (y.expand ρ)
  | .mul x y => .mul (x.expand ρ) (y.expand ρ)

theorem Expr.expand_eval {n : Nat} (ρ : Fin n → TermTriple) (e : Expr n) :
    (e.expand ρ).eval = e.eval (fun i => (ρ i).eval) := by
  induction e with
  | num k => exact numeralTerm_eval k
  | ref i s => exact TermTriple.get_eval (ρ i) s
  | add x y hx hy => simp [expand, ClosedTerm.eval, Expr.eval, hx, hy]
  | mul x y hx hy => simp [expand, ClosedTerm.eval, Expr.eval, hx, hy]

def Triple.expand {n : Nat} (ρ : Fin n → TermTriple) (t : Triple n) : TermTriple :=
  ⟨t.len.expand ρ, t.scale.expand ρ, t.payload.expand ρ⟩

theorem Triple.expand_eval {n : Nat} (ρ : Fin n → TermTriple) (t : Triple n) :
    (t.expand ρ).eval = t.eval (fun i => (ρ i).eval) := by
  simp [expand, TermTriple.eval, Triple.eval, Expr.expand_eval]

def Program.expansion {n : Nat} : Program n → Fin n → TermTriple
  | .nil => Fin.elim0
  | .snoc p t => Fin.lastCases (t.expand p.expansion) p.expansion

theorem Program.expansion_eval {n : Nat} (p : Program n) :
    (fun i => (p.expansion i).eval) = p.eval := by
  induction p with
  | nil => funext i; exact Fin.elim0 i
  | snoc p t ih =>
    funext i
    refine Fin.lastCases ?_ (fun j => ?_) i
    · simp only [expansion, Program.eval, Fin.lastCases_last, Triple.expand_eval, ih]
    · simp only [expansion, Program.eval, Fin.lastCases_castSucc]
      exact congrFun ih j

theorem compiled_expansion_value {b n : Nat} (g : Grammar b n) (i : Fin n) :
    ((compile g).expansion i).eval = quoteWord b (g.words i) := by
  have h := congrFun (Program.expansion_eval (compile g)) i
  rw [compile_correct] at h
  exact h

/-- The variable needed in the one universal axiom. All substituted terms are closed. -/
inductive Term where
  | var0 : Term
  | closed : ClosedTerm → Term
  deriving DecidableEq, Repr

inductive Formula where
  | eq : Term → Term → Formula
  | imp : Formula → Formula → Formula
  | all : Formula → Formula
  deriving DecidableEq, Repr

def universalRefl : Formula := .all (.eq .var0 .var0)
def reflFormula (t : ClosedTerm) : Formula := .eq (.closed t) (.closed t)
def instFormula (t : ClosedTerm) : Formula := .imp universalRefl (reflFormula t)

/-- An object calculus consisting only of three legal Enderton proof operations.
It is separate from Lean's theorem prover and contains no arithmetic truth oracle. -/
inductive EndertonFragment : Formula → Prop where
  | generalizedReflexivity : EndertonFragment universalRefl
  | closedInstantiation (t : ClosedTerm) : EndertonFragment (instFormula t)
  | mp {a f : Formula} : EndertonFragment a → EndertonFragment (.imp a f) → EndertonFragment f

theorem reflFormula_derivable (t : ClosedTerm) : EndertonFragment (reflFormula t) :=
  .mp .generalizedReflexivity (.closedInstantiation t)

/-- Two special cases of Enderton axiom groups 5 (generalized) and 2. -/
def axiomCheck (f : Formula) : Bool :=
  if f = universalRefl then true else
    match f with
    | .imp a (.eq (.closed t) (.closed u)) => decide (a = universalRefl ∧ t = u)
    | _ => false

theorem axiomCheck_universal : axiomCheck universalRefl = true := by
  simp [axiomCheck]

theorem axiomCheck_inst (t : ClosedTerm) : axiomCheck (instFormula t) = true := by
  simp [axiomCheck, instFormula, reflFormula, universalRefl]

inductive Line where
  | axiom : Formula → Line
  | mp : Nat → Nat → Formula → Line
  deriving DecidableEq, Repr

def checkStep (Γ : List Formula) : Line → Option (List Formula)
  | .axiom f => if axiomCheck f then some (Γ ++ [f]) else none
  | .mp a i f => do
    let antecedent ← Γ[a]?
    let implication ← Γ[i]?
    if implication = .imp antecedent f then some (Γ ++ [f]) else none

def checkLines : List Formula → List Line → Option (List Formula)
  | Γ, [] => some Γ
  | Γ, l :: ls => do
    let next ← checkStep Γ l
    checkLines next ls

def localLines : Nat → List ClosedTerm → List Line
  | _, [] => []
  | j, t :: ts => .axiom (instFormula t) :: .mp 0 j (reflFormula t) :: localLines (j + 2) ts

def localFormulas : List ClosedTerm → List Formula
  | [] => []
  | t :: ts => instFormula t :: reflFormula t :: localFormulas ts

theorem localFormulas_derivable (ts : List ClosedTerm) :
    ∀ f ∈ universalRefl :: localFormulas ts, EndertonFragment f := by
  intro f hf
  simp only [List.mem_cons] at hf
  rcases hf with rfl | hf
  · exact .generalizedReflexivity
  · induction ts with
    | nil => simp [localFormulas] at hf
    | cons t ts ih =>
      simp only [localFormulas, List.mem_cons] at hf
      rcases hf with rfl | rfl | hf
      · exact .closedInstantiation t
      · exact reflFormula_derivable t
      · exact ih hf

theorem first_survives_append (Γ Δ : List Formula) (h : Γ[0]? = some universalRefl) :
    (Γ ++ Δ)[0]? = some universalRefl := by
  cases Γ with
  | nil => simp at h
  | cons a as => simpa using h

theorem check_localLines (Γ : List Formula) (h : Γ[0]? = some universalRefl)
    (ts : List ClosedTerm) :
    checkLines Γ (localLines Γ.length ts) = some (Γ ++ localFormulas ts) := by
  induction ts generalizing Γ with
  | nil => simp [localLines, checkLines, localFormulas]
  | cons t ts ih =>
    have hf := first_survives_append Γ [instFormula t] h
    have hf2 := first_survives_append Γ [instFormula t, reflFormula t] h
    have hx : (Γ ++ [instFormula t])[Γ.length]? = some (instFormula t) := by simp
    have hs1 : checkStep Γ (.axiom (instFormula t)) = some (Γ ++ [instFormula t]) := by
      simp [checkStep, axiomCheck_inst]
    have hs2 : checkStep (Γ ++ [instFormula t]) (.mp 0 Γ.length (reflFormula t)) =
        some (Γ ++ [instFormula t] ++ [reflFormula t]) := by
      simp only [checkStep, hf, hx, bind, Option.bind]
      simp [instFormula]
    rw [localLines, checkLines, hs1]
    change checkLines (Γ ++ [instFormula t])
      (.mp 0 Γ.length (reflFormula t) :: localLines (Γ.length + 2) ts) = _
    rw [checkLines, hs2]
    change checkLines (Γ ++ [instFormula t] ++ [reflFormula t])
      (localLines (Γ.length + 2) ts) = _
    have hl : (Γ ++ [instFormula t, reflFormula t]).length = Γ.length + 2 := by simp
    rw [List.append_assoc]
    change checkLines (Γ ++ [instFormula t, reflFormula t]) (localLines (Γ.length + 2) ts) = _
    rw [← hl, ih _ hf2]
    simp [localFormulas, List.append_assoc]

def localCertificate (ts : List ClosedTerm) : List Line :=
  .axiom universalRefl :: localLines 1 ts

theorem localCertificate_checked (ts : List ClosedTerm) :
    checkLines [] (localCertificate ts) = some (universalRefl :: localFormulas ts) := by
  simp only [localCertificate, checkLines, checkStep, axiomCheck_universal, ↓reduceIte,
    List.nil_append, Option.bind_some]
  exact check_localLines [universalRefl] rfl ts

def Program.terms {n : Nat} : Program n → List ClosedTerm
  | .nil => []
  | .snoc p t =>
    let v := t.expand p.expansion
    p.terms ++ [v.len, v.scale, v.payload]

theorem Program.terms_length {n : Nat} (p : Program n) : p.terms.length = 3 * n := by
  induction p with
  | nil => rfl
  | snoc p t ih => simp [terms, ih]; omega

/-- The object-language certificate for every compiled program is accepted. -/
theorem compiled_localCertificate_checked {b n : Nat} (g : Grammar b n) :
    checkLines [] (localCertificate (compile g).terms) =
      some (universalRefl :: localFormulas (compile g).terms) :=
  localCertificate_checked _

def universalWire : List Char := "(Av0(=v0v0))".toList

def equationWire {n : Nat} (i : Nat) (e : Expr n) : List Char :=
  "(=".toList ++ identifier i ++ e.wire ++ [')']

/-- Define one term, instantiate universal reflexivity, and use modus ponens.
Formula indices count only axiom/MP records. -/
def certifiedDefinition {n : Nat} (s : Slot) (e : Expr n) : List Char :=
  let i := 3 * n + s.offset
  let q := equationWire i e
  definition n s e ++
    "A(>".toList ++ universalWire ++ q ++ ")\n".toList ++
    "M[".toList ++ identifier 0 ++ [','] ++ identifier (2 * i + 1) ++ [']'] ++ q ++ ['\n']

def Triple.certifiedWire {n : Nat} (t : Triple n) : List Char :=
  certifiedDefinition .len t.len ++ certifiedDefinition .scale t.scale ++
    certifiedDefinition .payload t.payload

def Program.certifiedBody {n : Nat} : Program n → List Char
  | .nil => []
  | .snoc p t => p.certifiedBody ++ t.certifiedWire

def Program.certifiedWire {n : Nat} (p : Program n) : List Char :=
  ['A'] ++ universalWire ++ ['\n'] ++ p.certifiedBody

theorem certifiedDefinition_length {n : Nat} (s : Slot) (e : Expr n) :
    (certifiedDefinition s e).length ≤ (40 * n + 100) * (e.weight + 1) := by
  have he := e.wire_length
  have hi := identifier_length_le (3 * n + s.offset)
  have hr := identifier_length_le (2 * (3 * n + s.offset) + 1)
  have hs := s.offset_le_two
  have he' : 3 * e.wire.length ≤ (40 * n + 100) * e.weight := by
    have hh := Nat.mul_le_mul_left 3 he
    have hk := Nat.mul_le_mul_right e.weight (show 3 * (6 * n + 7) ≤ 40 * n + 100 by omega)
    rw [Nat.mul_assoc] at hk
    exact Nat.le_trans hh hk
  simp only [certifiedDefinition, definition, equationWire, List.length_append,
    List.length_cons, List.length_nil]
  change 4 + (identifier (3 * n + s.offset)).length + 4 + e.wire.length + (1 + 0) +
    3 + 12 + (2 + (identifier (3 * n + s.offset)).length + e.wire.length + (1 + 0)) +
    2 + 2 + (identifier 0).length + (1 + 0) +
    (identifier (2 * (3 * n + s.offset) + 1)).length + (1 + 0) +
    (2 + (identifier (3 * n + s.offset)).length + e.wire.length + (1 + 0)) + (1 + 0) ≤ _
  have hz : (identifier 0).length = 4 := by simp [identifier, bits]
  rw [hz]
  simp only [Nat.mul_add, Nat.mul_one] at *
  omega

theorem Triple.certifiedWire_length {n : Nat} (t : Triple n) :
    t.certifiedWire.length ≤ (40 * n + 100) * (t.weight + 3) := by
  have hl := certifiedDefinition_length Slot.len t.len
  have hs := certifiedDefinition_length Slot.scale t.scale
  have hp := certifiedDefinition_length Slot.payload t.payload
  simp only [Triple.certifiedWire, List.length_append, Triple.weight]
  simp only [Nat.mul_add, Nat.mul_one] at *
  omega

theorem Program.certifiedBody_length {n : Nat} (p : Program n) :
    p.certifiedBody.length ≤ (40 * n + 100) * (p.weight + 3 * n) := by
  induction p with
  | nil => simp [certifiedBody, weight]
  | @snoc n p t ih =>
    have ht := t.certifiedWire_length
    have hs := Nat.mul_le_mul_right (p.weight + t.weight + 3 * n + 3)
      (show 40 * n + 100 ≤ 40 * (n + 1) + 100 by omega)
    simp only [certifiedBody, List.length_append, weight]
    have h : p.certifiedBody.length + t.certifiedWire.length ≤
        (40 * n + 100) * (p.weight + t.weight + 3 * n + 3) := by
      simp only [Nat.mul_add] at *
      omega
    calc
      _ ≤ (40 * n + 100) * (p.weight + t.weight + 3 * n + 3) := h
      _ ≤ (40 * (n + 1) + 100) * (p.weight + t.weight + 3 * n + 3) := hs
      _ = _ := by congr 1

theorem Program.certifiedWire_length {n : Nat} (p : Program n) :
    p.certifiedWire.length ≤ 20 + (40 * n + 100) * (p.weight + 3 * n) := by
  have h := p.certifiedBody_length
  simp only [certifiedWire, List.length_append, List.length_cons, List.length_nil]
  change (1 + 0) + 12 + (1 + 0) + p.certifiedBody.length ≤ _
  omega

/-- Character count includes definitions, all identifiers, instantiated axiom
records, MP records, and their line references. -/
theorem compile_certificate_characters {b n : Nat} (g : Grammar b n) :
    (compile g).certifiedWire.length ≤
      20 + (40 * g.mass + 100) * (4 * (b + 4) * g.mass ^ 2 + 3 * g.mass) := by
  have hw := (compile g).certifiedWire_length
  have ht := compile_weight g
  have hn := g.count_le_mass
  have ha : 40 * n + 100 ≤ 40 * g.mass + 100 := by omega
  have hb : (compile g).weight + 3 * n ≤
      4 * (b + 4) * g.mass ^ 2 + 3 * g.mass := by omega
  have hh := Nat.mul_le_mul ha hb
  omega

theorem compile_certificate_with_budget {b n : Nat} (g : Grammar b n) (k : Nat)
    (hk : g.mass ≤ k) :
    (compile g).certifiedWire.length ≤
      20 + (40 * k + 100) * (4 * (b + 4) * k ^ 2 + 3 * k) := by
  have h := compile_certificate_characters g
  have hsq : g.mass ^ 2 ≤ k ^ 2 := by
    simpa [Nat.pow_succ] using Nat.mul_le_mul hk hk
  have hc := Nat.mul_le_mul_left (4 * (b + 4)) hsq
  have h₁ : 40 * g.mass + 100 ≤ 40 * k + 100 := by omega
  have h₂ : 4 * (b + 4) * g.mass ^ 2 + 3 * g.mass ≤
      4 * (b + 4) * k ^ 2 + 3 * k := by omega
  have hh := Nat.mul_le_mul h₁ h₂
  omega

end MAISO11.Quotation
